server:
  port: 8010
  tomcat:
    accept-count: 1000
    max-connections: 2000
    threads:
      max: 500
spring:
  main:
    allow-bean-definition-overriding: true
  ai:
    ollama:
      base-url: http://127.0.0.1:11434/
      chat:
        options:
#          model: llama3.1
          model: qwen2
          temperature: 0.7
      embedding:
        model: mofanke/dmeta-embedding-zh
#        model: llama3.1
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        ##embedding的向量维度，这里的768是根据nomic-embed-text返回的向量维度配置的。pgvector最大支持2000维度
        dimensions: 768
  datasource:
    postgresql:
      jdbcUrl: jdbc:postgresql://127.0.0.1:5416/postgres
      url: jdbc:postgresql://127.0.0.1:5416/postgres
      username: postgres
      password:
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 'ikazuchi'
      jdbcUrl: jdbc:mysql://localhost:3306/chatbot_dev?allowMultiQueries=true
      url: jdbc:mysql://localhost:3306/chatbot_dev?allowMultiQueries=true
      username: root
#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml