server:
  port: 8089
  tomcat:
    accept-count: 1000
    max-connections: 2000
    threads:
      max: 500
spring:
  ai:
    ollama:
      base-url: http://127.0.0.1:11434/
      chat:
        options:
          #          model: llama3.1
          model: qwen2
          temperature: 0.7
      embedding:
        model: mofanke/dmeta-embedding-zh
  #        model: llama3.1
  datasource:
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 'ikazuchi'
      jdbcUrl: jdbc:mysql://localhost:3306/chatbot_dev?allowMultiQueries=true
      url: jdbc:mysql://localhost:3306/chatbot_dev?allowMultiQueries=true
      username: root
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml